### PR TITLE
Attempt to fix job_run issue in staging

### PR DESCRIPTION
**Pull request by ChrisPRobinson**

### CODE REVIEW

**Comment by ChrisPRobinson** [comment]
@emya I accidentally removed the success? method, adding it back in and tweaking things a bit. Hoping this is the last issue from my change.

**Comment by emya** [comment]
I see, Thank you for fixing this issue.

**Comment by ChrisPRobinson** [comment]
@emya Needed to update various tests. I needed to ensure the string has been properly symbolized

**Comment by emya** [comment]
OK, please feel free to merge the PR if all tests are passed.

**Pull request merged**
